version: "3"

services:
  node:
    build: .
    image: node:alpine
    depends_on: 
    - redis
    - postgres
    container_name: node
    ports:
    - "3333:3333"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
    - "6379:6379"
  postgres:
    image: postgres
    container_name: postgres
    ports: 
    - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
